GET http://localhost:3000/auth

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Humayun",
    "email": "raahat.rashid09@gmail.com",
    "password": "123"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "Humayun",
    "email": "raahat.rashid09@gmail.com",
    "password": "123"
}
